trigger_branches = [
'Bu_L0Global_Dec', 
'Bu_L0Global_TIS', 
'Bu_L0Global_TOS', 
# 'Bu_Hlt1Global_Dec', 
# 'Bu_Hlt1Global_TIS', 
# 'Bu_Hlt1Global_TOS', 
# 'Bu_Hlt1Phys_Dec', 
# 'Bu_Hlt1Phys_TIS', 
# 'Bu_Hlt1Phys_TOS', 
# 'Bu_Hlt2Global_Dec', 
# 'Bu_Hlt2Global_TIS', 
# 'Bu_Hlt2Global_TOS', 
# 'Bu_Hlt2Phys_Dec', 
# 'Bu_Hlt2Phys_TIS', 
# 'Bu_Hlt2Phys_TOS', 
# 'Bu_L0GlobalDecision_Dec', 
# 'Bu_L0GlobalDecision_TIS', 
# 'Bu_L0GlobalDecision_TOS', 
# 'Bu_L0PhysDecision_Dec', 
# 'Bu_L0PhysDecision_TIS', 
# 'Bu_L0PhysDecision_TOS', 
# 'Bu_L0HadronDecision_Dec', 
'Bu_L0HadronDecision_TIS', 
'Bu_L0HadronDecision_TOS', 
'Bu_L0MuonDecision_Dec', 
'Bu_L0MuonDecision_TIS', 
'Bu_L0MuonDecision_TOS', 
'Bu_L0MuonHighDecision_Dec', 
'Bu_L0MuonHighDecision_TIS', 
'Bu_L0MuonHighDecision_TOS', 
'Bu_L0DiMuonDecision_Dec', 
'Bu_L0DiMuonDecision_TIS', 
'Bu_L0DiMuonDecision_TOS', 
# 'Bu_L0PhotonDecision_Dec', 
# 'Bu_L0PhotonDecision_TIS', 
# 'Bu_L0PhotonDecision_TOS', 
# 'Bu_L0ElectronDecision_Dec', 
# 'Bu_L0ElectronDecision_TIS', 
# 'Bu_L0ElectronDecision_TOS', 
'Bu_Hlt1TrackMVADecision_Dec', 
'Bu_Hlt1TrackMVADecision_TIS', 
'Bu_Hlt1TrackMVADecision_TOS', 
'Bu_Hlt1TrackMVALooseDecision_Dec', 
'Bu_Hlt1TrackMVALooseDecision_TIS', 
'Bu_Hlt1TrackMVALooseDecision_TOS', 
'Bu_Hlt1TwoTrackMVADecision_Dec', 
'Bu_Hlt1TwoTrackMVADecision_TIS', 
'Bu_Hlt1TwoTrackMVADecision_TOS', 
# 'Bu_Hlt1TwoTrackMVALooseDecision_Dec', 
# 'Bu_Hlt1TwoTrackMVALooseDecision_TIS', 
# 'Bu_Hlt1TwoTrackMVALooseDecision_TOS', 
# 'Bu_Hlt1TrackMuonDecision_Dec', 
# 'Bu_Hlt1TrackMuonDecision_TIS', 
# 'Bu_Hlt1TrackMuonDecision_TOS', 
# 'Bu_Hlt1TrackMuonMVADecision_Dec', 
# 'Bu_Hlt1TrackMuonMVADecision_TIS', 
# 'Bu_Hlt1TrackMuonMVADecision_TOS', 
# 'Bu_Hlt1DiMuonHighMassDecision_Dec', 
# 'Bu_Hlt1DiMuonHighMassDecision_TIS', 
# 'Bu_Hlt1DiMuonHighMassDecision_TOS', 
# 'Bu_Hlt1DiMuonLowMassDecision_Dec', 
# 'Bu_Hlt1DiMuonLowMassDecision_TIS', 
# 'Bu_Hlt1DiMuonLowMassDecision_TOS', 
# 'Bu_Hlt1DiMuonNoL0Decision_Dec', 
# 'Bu_Hlt1DiMuonNoL0Decision_TIS', 
# 'Bu_Hlt1DiMuonNoL0Decision_TOS', 
# 'Bu_Hlt1SingleMuonNoIPDecision_Dec', 
# 'Bu_Hlt1SingleMuonNoIPDecision_TIS', 
# 'Bu_Hlt1SingleMuonNoIPDecision_TOS', 
# 'Bu_Hlt1SingleMuonHighPTDecision_Dec', 
# 'Bu_Hlt1SingleMuonHighPTDecision_TIS', 
# 'Bu_Hlt1SingleMuonHighPTDecision_TOS', 
# 'Bu_Hlt1L0AnyDecision_Dec', 
# 'Bu_Hlt1L0AnyDecision_TIS', 
# 'Bu_Hlt1L0AnyDecision_TOS', 
# 'Bu_Hlt1MBNoBiasDecision_Dec', 
# 'Bu_Hlt1MBNoBiasDecision_TIS', 
'Bu_Hlt1MBNoBiasDecision_TOS', 
'Bu_Hlt2Topo2BodyDecision_Dec', 
'Bu_Hlt2Topo2BodyDecision_TIS', 
'Bu_Hlt2Topo2BodyDecision_TOS', 
'Bu_Hlt2Topo3BodyDecision_Dec', 
'Bu_Hlt2Topo3BodyDecision_TIS', 
'Bu_Hlt2Topo3BodyDecision_TOS', 
'Bu_Hlt2Topo4BodyDecision_Dec', 
'Bu_Hlt2Topo4BodyDecision_TIS', 
'Bu_Hlt2Topo4BodyDecision_TOS', 
# 'Bu_Hlt2Topo2BodyBBDTDecision_Dec', 
# 'Bu_Hlt2Topo2BodyBBDTDecision_TIS', 
# 'Bu_Hlt2Topo2BodyBBDTDecision_TOS', 
# 'Bu_Hlt2Topo3BodyBBDTDecision_Dec', 
# 'Bu_Hlt2Topo3BodyBBDTDecision_TIS', 
# 'Bu_Hlt2Topo3BodyBBDTDecision_TOS', 
# 'Bu_Hlt2Topo4BodyBBDTDecision_Dec', 
# 'Bu_Hlt2Topo4BodyBBDTDecision_TIS', 
# 'Bu_Hlt2Topo4BodyBBDTDecision_TOS', 
# 'Bu_Hlt2DiMuonBDecision_Dec', 
# 'Bu_Hlt2DiMuonBDecision_TIS', 
# 'Bu_Hlt2DiMuonBDecision_TOS', 
# 'Bu_Hlt2DiMuonBTurboDecision_Dec', 
# 'Bu_Hlt2DiMuonBTurboDecision_TIS', 
# 'Bu_Hlt2DiMuonBTurboDecision_TOS', 
# 'Bu_Hlt2DiMuonDetachedDecision_Dec', 
# 'Bu_Hlt2DiMuonDetachedDecision_TIS', 
# 'Bu_Hlt2DiMuonDetachedDecision_TOS', 
# 'Bu_Hlt2DiMuonDetachedHeavyDecision_Dec', 
# 'Bu_Hlt2DiMuonDetachedHeavyDecision_TIS', 
# 'Bu_Hlt2DiMuonDetachedHeavyDecision_TOS', 
# 'Bu_Hlt2DiMuonDetachedJPsiDecision_Dec', 
# 'Bu_Hlt2DiMuonDetachedJPsiDecision_TIS', 
# 'Bu_Hlt2DiMuonDetachedJPsiDecision_TOS', 
# 'Bu_Hlt2DiMuonDetachedPsi2SDecision_Dec', 
# 'Bu_Hlt2DiMuonDetachedPsi2SDecision_TIS', 
# 'Bu_Hlt2DiMuonDetachedPsi2SDecision_TOS', 
# 'Bu_Hlt2DiMuonJPsiDecision_Dec', 
# 'Bu_Hlt2DiMuonJPsiDecision_TIS', 
# 'Bu_Hlt2DiMuonJPsiDecision_TOS', 
# 'Bu_Hlt2DiMuonJPsiHighPTDecision_Dec', 
# 'Bu_Hlt2DiMuonJPsiHighPTDecision_TIS', 
# 'Bu_Hlt2DiMuonJPsiHighPTDecision_TOS', 
# 'Bu_Hlt2DiMuonJPsiTurboDecision_Dec', 
# 'Bu_Hlt2DiMuonJPsiTurboDecision_TIS', 
# 'Bu_Hlt2DiMuonJPsiTurboDecision_TOS', 
# 'Bu_Hlt2DiMuonPsi2SDecision_Dec', 
# 'Bu_Hlt2DiMuonPsi2SDecision_TIS', 
# 'Bu_Hlt2DiMuonPsi2SDecision_TOS', 
# 'Bu_Hlt2DiMuonPsi2SHighPTDecision_Dec', 
# 'Bu_Hlt2DiMuonPsi2SHighPTDecision_TIS', 
# 'Bu_Hlt2DiMuonPsi2SHighPTDecision_TOS', 
# 'Bu_Hlt2DiMuonPsi2STurboDecision_Dec', 
# 'Bu_Hlt2DiMuonPsi2STurboDecision_TIS', 
# 'Bu_Hlt2DiMuonPsi2STurboDecision_TOS', 
# 'Bu_Hlt2DiMuonSoftDecision_Dec', 
# 'Bu_Hlt2DiMuonSoftDecision_TIS', 
# 'Bu_Hlt2DiMuonSoftDecision_TOS', 
# 'Bu_Hlt2TopoMu2BodyDecision_Dec', 
# 'Bu_Hlt2TopoMu2BodyDecision_TIS', 
# 'Bu_Hlt2TopoMu2BodyDecision_TOS', 
# 'Bu_Hlt2TopoMu3BodyDecision_Dec', 
# 'Bu_Hlt2TopoMu3BodyDecision_TIS', 
# 'Bu_Hlt2TopoMu3BodyDecision_TOS', 
# 'Bu_Hlt2TopoMu4BodyDecision_Dec', 
# 'Bu_Hlt2TopoMu4BodyDecision_TIS', 
# 'Bu_Hlt2TopoMu4BodyDecision_TOS', 
# 'Bu_Hlt2TopoMuMu2BodyDecision_Dec', 
# 'Bu_Hlt2TopoMuMu2BodyDecision_TIS', 
# 'Bu_Hlt2TopoMuMu2BodyDecision_TOS', 
# 'Bu_Hlt2TopoMuMu3BodyDecision_Dec', 
# 'Bu_Hlt2TopoMuMu3BodyDecision_TIS', 
# 'Bu_Hlt2TopoMuMu3BodyDecision_TOS', 
# 'Bu_Hlt2TopoMuMu4BodyDecision_Dec', 
# 'Bu_Hlt2TopoMuMu4BodyDecision_TIS', 
# 'Bu_Hlt2TopoMuMu4BodyDecision_TOS', 
# 'Bu_Hlt2GlobalDecision_Dec', 
# 'Bu_Hlt2GlobalDecision_TIS', 
# 'Bu_Hlt2GlobalDecision_TOS'
]